In [1]:
#Importing necessary libraries
import pandas as pd
import gradio as gr
from sklearn.metrics.pairwise import cosine_similarity

c:\Users\saadt\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#Loading Dataset
data = pd.read_csv('books_rating.csv')
data.head()

   user_id               book_title  rating
0       91       The Power of Habit     1.4
1       48              The Odyssey     3.9
2       21               The Prince     2.0
3       58  Where the Crawdads Sing     4.4
4       49                 Becoming     4.0

In [3]:
#Creating user book matrix
user_book_matrix = data.pivot_table(index='user_id', columns='book_title', values = 'rating').fillna(0)
user_book_matrix

book_title,12 Rules for Life,1984,A Man Called Ove,A Tale of Two Cities,Animal Farm,Anna Karenina,Atomic Habits,Becoming,Beloved,Blink,...,The Stand,The Subtle Art of Not Giving a F*ck,Things Fall Apart,Think and Grow Rich,"Thinking, Fast and Slow",To Kill a Mockingbird,Twilight,War and Peace,Where the Crawdads Sing,Wuthering Heights
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,...,2.4,0.0,0.0,0.0,0.0,4.5,0.0,0.0,0.0,1.8
2,0.0,0.0,0.0,3.7,0.0,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.10,...,0.0,0.0,2.2,4.8,1.8,0.0,0.0,0.0,0.0,0.0
4,0.0,4.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.80,...,1.4,0.0,0.0,0.0,2.4,0.0,4.9,0.0,0.0,0.0
5,0.0,0.0,2.0,0.0,0.0,2.2,2.3,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.5,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.0,3.5,0.0,0.0,3.9,0.0,0.0,0.0,0.0,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.1,0.0,0.00,...,0.0,4.9,0.0,4.5,0.0,0.0,4.2,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.5,0.00,...,2.5,0.0,0.0,0.0,2.4,0.0,0.0,0.0,0.0,0.0
99,0.0,3.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.65,...,0.0,3.8,1.5,0.0,0.0,0.0,2.9,4.8,0.0,0.0
100,0.0,0.0,0.0,0.0,0.0,3.3,0.0,3.8,0.0,0.00,...,0.0,0.0,0.0,1.3,0.0,3.8,4.9,0.0,0.0,0.0

In [4]:
#Calculating cosine similarity between users
user_similarity = cosine_similarity(user_book_matrix)
user_similarity_df = pd.DataFrame(user_similarity, index=user_book_matrix.index, columns=user_book_matrix.index)
user_similarity_df

user_id,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.115619,0.044574,0.019342,0.044847,0.175642,0.075600,0.182580,0.256266,0.069693,...,0.142394,0.332050,0.385177,0.124533,0.297308,0.193007,0.000000,0.255367,0.098638,0.084017
2,0.115619,1.000000,0.034650,0.099784,0.308324,0.057035,0.183126,0.170414,0.100769,0.113601,...,0.000000,0.118978,0.155111,0.080248,0.076725,0.225440,0.135198,0.137283,0.218493,0.171536
3,0.044574,0.034650,1.000000,0.084292,0.323142,0.174033,0.270722,0.213108,0.258633,0.339547,...,0.103268,0.147550,0.115460,0.155892,0.168964,0.205992,0.143235,0.260505,0.142623,0.138844
4,0.019342,0.099784,0.084292,1.000000,0.029511,0.371661,0.092189,0.108501,0.016894,0.061382,...,0.295029,0.210681,0.016288,0.017118,0.251079,0.171352,0.192359,0.113136,0.207185,0.170711
5,0.044847,0.308324,0.323142,0.029511,1.000000,0.212886,0.327535,0.361016,0.345118,0.231857,...,0.130836,0.213157,0.240696,0.086459,0.175560,0.159052,0.138216,0.047792,0.112386,0.256226
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.193007,0.225440,0.205992,0.171352,0.159052,0.161811,0.059329,0.102931,0.000000,0.230430,...,0.258961,0.116426,0.151356,0.060370,0.098161,1.000000,0.000000,0.041180,0.166872,0.129974
97,0.000000,0.135198,0.143235,0.192359,0.138216,0.000000,0.183339,0.122541,0.085743,0.164613,...,0.000000,0.054595,0.222254,0.219261,0.236898,0.000000,1.000000,0.026752,0.210964,0.178669
98,0.255367,0.137283,0.260505,0.113136,0.047792,0.127065,0.136767,0.076261,0.103828,0.119532,...,0.050575,0.271332,0.132432,0.154338,0.114372,0.041180,0.026752,1.000000,0.084078,0.025547
99,0.098638,0.218493,0.142623,0.207185,0.112386,0.270098,0.197497,0.141399,0.015071,0.238593,...,0.131031,0.112179,0.169958,0.089334,0.230538,0.166872,0.210964,0.084078,1.000000,0.076872
100,0.084017,0.171536,0.138844,0.170711,0.256226,0.087831,0.212967,0.135404,0.146796,0.195611,...,0.161885,0.278664,0.137911,0.272646,0.198591,0.129974,0.178669,0.025547,0.076872,1.000000

In [5]:
# Function to recommend books based on user similarity
def recommend_books(user_id, top_n=3):
    if user_id not in user_similarity_df.index:
        return ["User not found in the dataset."]

    similar_users = user_similarity_df[user_id].sort_values(ascending=False).drop(user_id)

    recommended_books = {}
    for sim_user, similarity in similar_users.items():
        rated_books = user_book_matrix.loc[sim_user]
        for book, rating in rated_books[rated_books > 0].items():
            if user_book_matrix.loc[user_id, book] == 0:
                recommended_books[book] = recommended_books.get(book, 0) + rating * similarity

    recommended_books = sorted(recommended_books.items(), key=lambda x: x[1], reverse=True)
    return [book for book, _ in recommended_books[:top_n]]

In [6]:
#Gradio interface & User Input
demo = gr.Interface(
    fn = recommend_books,
    inputs = [
        gr.Number(label="Enter User ID (1-100)", precision=0),
        gr.Number(label="Number of Books to Recommend", value=3, precision=0)

    ],
    outputs = gr.List(label="Recommended Books"),
    title = "Book Recommendation System",
    description = "Enter a user ID to get personalized book recommendations based on other users' ratings."
)

In [7]:
#Calling Function
demo.launch()

* Running on local URL:  http://127.0.0.1:7860
* To create a public link, set `share=True` in `launch()`.